[build]
builder = "dockerfile"

[deploy]
startCommand = "/opt/airflow/scripts/init.sh && airflow webserver --port $PORT"

[[services]]
name = "yucatan-web"
internal_port = 8080
public_port = 8080
protocol = "http"

[[services]]
name = "yucatan-scheduler"
startCommand = "airflow scheduler"

[[services]]
name = "yucatan-worker"
startCommand = "airflow celery worker"
