[build]
builder = "dockerfile"

[deploy]
# El ';' asegura que el webserver arranque aunque el init tire un aviso
startCommand = "bash /opt/airflow/scripts/init.sh ; airflow webserver --port $PORT"

[[services]]
name = "yucatan-web"
internal_port = 8080
public_port = 8080
protocol = "http"
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "yucatan-scheduler"
startCommand = "airflow scheduler"

[[services]]
name = "yucatan-worker"
startCommand = "airflow celery worker"

[env]
AIRFLOW_HOME = "/opt/airflow"
AIRFLOW__CORE__LOAD_EXAMPLES = "False"
AIRFLOW__CORE__EXECUTOR = "CeleryExecutor"
# LLAVE FERNET CRITICA (DEBE SER 32 BYTES BASE64)
AIRFLOW__CORE__FERNET_KEY = "7X7lR9-5X-W2u8W8x9X_Y7z6W5v4U3t2S1R0PqOnMlKj="
PYTHONUNBUFFERED = "1"
